import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
const accepted=['image/jpeg','image/png','image/webp','image/avif','audio/mpeg','audio/ogg','audio/wav','application/pdf'];
export default function MediaLibrary(){
 const [assets,setAssets]=useState([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[preview,setPreview]=useState(null),[file,setFile]=useState(null),[alt,setAlt]=useState('');
 useEffect(()=>{let live=true;supabase.from('media_assets').select('*').order('created_at',{ascending:false}).then(({data,error})=>{if(!live)return;if(error)setError(error.message);else setAssets(data||[]);});return()=>{live=false;};},[revision]);
 const upload=async()=>{if(!file)return;if(!accepted.includes(file.type)||file.size>20*1024*1024||file.size===0){setError('Choose a JPEG, PNG, WebP, AVIF, MP3, OGG, WAV or PDF up to 20 MB.');return;}if(file.type.startsWith('image/')&&!alt.trim()){setError('Describe this image before uploading.');return;}setBusy(true);setError('');setNotice('');try{
 const id=crypto.randomUUID(),extension=file.name.split('.').pop().replace(/[^a-z0-9]/gi,'').toLowerCase(),path=`${id}.${extension||'bin'}`;
 const {error:uploadError}=await supabase.storage.from('journey-drafts').upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;
 const {error:dbError}=await supabase.from('media_assets').insert({id,path,name:file.name,mime:file.type,size:file.size,alt,visibility:'private'});if(dbError)throw Error('File uploaded privately, but metadata could not be saved. '+dbError.message+' Path: '+path);
 setNotice('Uploaded privately. Use Publish asset when this file is ready for public access.');setFile(null);setAlt('');setRevision(n=>n+1);
 }catch(e){setError(e.message);}finally{setBusy(false);}};
 const view=async a=>{setError('');if(a.visibility==='public'){setPreview({...a,url:supabase.storage.from('journey-media').getPublicUrl(a.path).data.publicUrl});return;}const {data,error}=await supabase.storage.from('journey-drafts').createSignedUrl(a.path,300);if(error)setError(error.message);else setPreview({...a,url:data.signedUrl});};
 const publish=async a=>{if(!window.confirm('Publish '+a.name+'? Anyone with its URL will be able to access this file. This action does not publish a journal entry.'))return;setBusy(true);setError('');try{
 const {error:copyError}=await supabase.storage.from('journey-drafts').copy(a.path,a.path,{destinationBucket:'journey-media'});
 if(copyError&&copyError.statusCode!=='409'&&copyError.statusCode!==409)throw copyError;
 const {data,error:saveError}=await supabase.from('media_assets').update({visibility:'public'}).eq('id',a.id).eq('updated_at',a.updated_at).select();if(saveError)throw saveError;if(!data?.length)throw Error('Metadata changed. Refresh the library. The file was copied publicly.');setRevision(n=>n+1);setNotice('Asset published. Copy its URL into an image, resume or music field.');
 }catch(e){setError(e.message);}finally{setBusy(false);}};
 const copy=async a=>{try{await navigator.clipboard.writeText(supabase.storage.from('journey-media').getPublicUrl(a.path).data.publicUrl);setNotice('Public URL copied.');}catch{setPreview({...a,url:supabase.storage.from('journey-media').getPublicUrl(a.path).data.publicUrl});}};
 return <><p className="cms-description">Uploads start private. Publishing makes a file publicly accessible by URL. Archiving an entry does not revoke an already published file.</p><section className="card"><h3>Upload media</h3><label className="input-group">Image, audio or resume PDF · up to 20 MB<input key={file?.name||'empty'} type="file" accept={accepted.join(',')} disabled={busy} onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label className="input-group">Image description<input type="text" value={alt} disabled={busy} onChange={e=>setAlt(e.target.value)}/></label><button className="btn btn-primary" disabled={busy||!file} onClick={upload}>{busy?'Working…':'Upload privately'}</button></section>{error&&<p role="alert" className="cms-error">{error}</p>}{notice&&<p role="status" className="cms-success">{notice}</p>}<div className="cms-media-grid">{assets.map(a=><article className="card" key={a.id}><span className="cms-badge">{a.visibility}</span><h3>{a.name}</h3><p>{a.alt||a.mime}</p><small>{(a.size/1024/1024).toFixed(2)} MB</small><div className="cms-toolbar"><button className="btn btn-outline" disabled={busy} onClick={()=>view(a)}>Preview</button>{a.visibility==='public'?<button className="btn btn-outline" onClick={()=>copy(a)}>Copy URL</button>:<button className="btn btn-primary" disabled={busy} onClick={()=>publish(a)}>Publish asset</button>}</div></article>)}</div>{preview&&<section className="card cms-media-preview"><button className="btn btn-outline" onClick={()=>setPreview(null)}>Close preview</button><h3>{preview.name}</h3>{preview.mime.startsWith('image/')?<img src={preview.url} alt={preview.alt}/>:preview.mime.startsWith('audio/')?<audio src={preview.url} controls/>:<a href={preview.url} target="_blank" rel="noreferrer">Open PDF</a>}{preview.visibility==='public'&&<label className="input-group">Public URL<input readOnly value={preview.url}/></label>}</section>}</>;
}
